services:
#  sekai_bridge_node1:
#    build:
#      context: ./sekai_bridge
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    expose:
#      - "8885:8885"
#      - "8886:8886"
#      - "9000:9000"
#    volumes:
#      - ./sekai_bridge/config.yml:/app/config.yml
#      - ./sekai_bridge/key.json:/app/key.json
#  sekai_bridge_node2:
#    build:
#      context: ./sekai_bridge
#      dockerfile: Dockerfile
#    depends_on:
#      - sekai_bridge_node1
#    expose:
#      - "8081:8081"
#      - "8887:8887"
#      - "8888:8888"
#    volumes:
#      - ./sekai_bridge/config2.yml:/app/config.yml
#      - ./sekai_bridge/key2.json:/app/key.json
  sekai_bridge_node:
    restart: always
    build:
      context: ./sekai_bridge
      dockerfile: Dockerfile
    expose:
      - "8082:8082"
      - "8889:8889"
      - "8890:8890"
    ports:
      - "9000:9000/udp"
    volumes:
      - ./sekai_bridge/config3.yml:/app/config.yml
      - ./sekai_bridge/key3.json:/app/key.json

  sai-eth-indexer:
    restart: always
    build:
      context: ./saiEthIndexer
      dockerfile: Dockerfile
    expose:
      - "8881:8881"
    volumes:
      - ./saiEthIndexer/block.data:/srv/block.data
      - ./saiEthIndexer/config.json:/srv/config.json
      - ./saiEthIndexer/contracts.json:/srv/contracts.json

  sai-eth-interaction:
    restart: always
    build:
      context: ./saiETHContractInteraction
      dockerfile: Dockerfile
    expose:
      - "8882:8882"
    volumes:
      - ./saiETHContractInteraction/config.yml:/srv/config.yml

  sai-cosmos-indexer:
    restart: always
    build:
      context: ./sai-cosmos-indexer
      dockerfile: Dockerfile
    expose:
      - "8883:8883"
    volumes:
      - ./sai-cosmos-indexer/config.yml:/srv/config.yml

  sai-cosmos-interaction:
    restart: always
    build:
      context: ./sai-cosmos-interaction
      dockerfile: Dockerfile
    expose:
      - "8884:8884"
    volumes:
      - ./sai-cosmos-interaction/config.yml:/srv/config.yml

  sai-storage:
    restart: always
    build:
      context: ./sai-storage-mongo
      dockerfile: Dockerfile
    expose:
      - "8880:8880"
    depends_on:
      - mongo-db
    volumes:
      - ./sai-storage-mongo/config.yml:/srv/config.yml


  mongo-db:
    restart: always
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: { }
