common:
  http:
    enabled: true
    port: 8888
  ws:
    enabled: false
    port: 9080
  log_mode: debug
p2p:
  port: 9000
  slot: 4
  http:
    port: 8887
http:
  port: 8081
udp:
  bufferSize: 40000
  interval: 100ms
peers:
  - node1:9000
tss:
  public_key: "2"
  parties: 3
  threshold: 2
  quorum: 2
token: "lafijsiadnm/a@@#lsa$fd8f"
debug: true
cache: ## cache settings
  ttl: 120 ## ttl for entry in cache in seconds
  clean: 240 ## when ttl expired entries should be cleaned in seconds
interaction:
  ethereum: "http://localhost:8882"
  cosmos: "http://localhost:8884"
