p2p:
  port: 9000
  slot: 3
peers:
#  - 127.0.0.1:9000
http:
  port: 8080
debug: true
udp:
  bufferSize: 40000
  interval: 100ms
cache: ## cache settings
  ttl: 120 ## ttl for entry in cache in seconds
  clean: 240 ## when ttl expired entries should be cleaned in seconds
